---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-spring-boot-api-84156f3f          # Service name
  labels:
    app: my-spring-boot-api-84156f3f
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: my-spring-boot-api-84156f3f         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080  # Target container port
